# reference: https://github.com/devops-recipes/prov_aws_vpc_ansible/blob/master/ansible/vpc_prov_playbook.yml
---
    - name: Create the VPC
      ec2_vpc_net:
        name: openshift_onap
        cidr_block: 10.10.0.0/16
        region: "{{ aws_region }}"
        state: present
        tags: { "NetworkSpace" : "ONAP" }
      register: this_vpc

    - name: Set VPC ID variable
      set_fact:
        vpc_id: "{{ this_vpc.vpc.id }}"

    - name: Create the subnet for the VPC
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        cidr: 10.10.10.0/24
        az: "{{ aws_region }}a"
        region: "{{ aws_region }}"
        tags: { "NetworkSpace" : "ONAP", "Network" : "External" }
      register: this_vpc_subnet

    - name: Set VPC Subnet ID variable
      set_fact:
        vpc_subnet_id: "{{ this_vpc_subnet.subnet.id }}"

    - name: Create a gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        state: present
        tags: { "NetworkSpace" : "ONAP", "Network" : "External" }
      register: this_vpc_igw

    - name: Set VPC gateway variable
      set_fact:
        igw_id: "{{ this_vpc_igw.gateway_id }}"

    - name: Create route
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        tags: { "NetworkSpace" : "ONAP", "Network" : "External" }
        subnets:
          - "{{ vpc_subnet_id }}"
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ igw_id }}"

    - name: Create initial security group for SSH login
      ec2_group:
        name: "openshift_onap"
        description: "Security group for ONAP on OpenShift"
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        tags: { "NetworkSpace" : "ONAP", "Network" : "External" }
        rules:
          - proto: "tcp"
            from_port: "22"
            to_port: "22"
            cidr_ip: "0.0.0.0/0"
      register: this_vpc_security_group

    - name: Set security group variable
      set_fact:
        sg_id: "{{ this_vpc_security_group.group_id }}"
